/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AntDesignSafetyCertificateOutlined: typeof import('~icons/ant-design/safety-certificate-outlined')['default']
    AntKeyOutlined: typeof import('~icons/ant-design/key-outlined')['default']
    AntLockOutlined: typeof import('~icons/ant-design/lock-outlined')['default']
    AntMenuOutlined: typeof import('~icons/ant-design/menu-outlined')['default']
    AntMessageFilled: typeof import('~icons/ant-design/message-filled')['default']
    AntSettingOutlined: typeof import('~icons/ant-design/setting-outlined')['default']
    AntUserOutlined: typeof import('~icons/ant-design/user-outlined')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBarMenu: typeof import('./src/components/sideBar/sideBarMenu.vue')['default']
  }
}
